// ==== DATI CARICATI CORRETTAMENTE DALL'API ====
// ==== VERIFICA RENDERING LISTA PRODOTTI ====
// ==== ORDINAMENTO, FILTRI, PAGINAZIONE ====
// ==== CONTROLLO ERRORI SE L'API RITORNA 500O DATI VUOTI ====
// ==== VERIFICA RENDERING LISTA PRODOTTI ====
// ==== RESPONSIVE ====